; -*- lexical-binding: t -*-

(package "svg-margin"
; x-release-please-start-version
         "0.1.4"
; x-release-please-end
         "Multi-provider SVG indicators in the window margins")

(website-url "https://github.com/chiply/svg-margin")
(keywords "convenience" "faces" "frames")

(package-file "svg-margin.el")
(files "*.el")

(script "test" "eask test ert test/svg-margin-test.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "29.1")

(development
 (depends-on "package-lint")
 (depends-on "elisp-lint")
 (depends-on "relint"))
